import type { Metadata, Viewport } from "next";
import { ConfigProvider } from "antd";
import FetchProvider from "@/contexts/FetchContext";
import PageSettingProvider from "@/contexts/PageSettingContext";
import "./globals.css";
import Header from "@/components/main/Header/Header";
import Footer from "@/components/main/Footer/Footer";
import { Noto_Sans_Thai_Looped } from "next/font/google";
const roboto = Noto_Sans_Thai_Looped({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Rent",
  description: "Generated by At-Once Teams.",
  // icons: [{ rel: "icon", url: Favicon.src }],
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <ConfigProvider
        theme={{
          token: {
            fontFamily: roboto.style.fontFamily,
          },
        }}
      >
        <FetchProvider>
          <PageSettingProvider>
            <body className={roboto.className}>
              <Header />
              {children}
              <Footer />
            </body>
          </PageSettingProvider>
        </FetchProvider>
      </ConfigProvider>
    </html>
  );
}
