import type { Metadata, Viewport } from "next";
import { ConfigProvider } from "antd";
import FetchProvider from "@/contexts/FetchContext";
import PageSettingProvider from "@/contexts/PageSettingContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Rent",
  description: "Generated by At-Once Teams.",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <ConfigProvider>
          <FetchProvider>
            <PageSettingProvider>
              <body>
                {children}
              </body>
            </PageSettingProvider>
          </FetchProvider>
        </ConfigProvider>
    </html>
  )
}
