import type { Metadata, Viewport } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/main/Header/Header";
// import Loading from "@/components/main/Loading/Loading";
import PageSettingProvider from "@/contexts/PageSettingContext";
import Footer from "@/components/main/Footer/Footer";
c
import Favicon from "../../../public/icon.ico";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import styles from "../../css/Component.module.scss";
import { ConfigProvider } from "antd";
import FetchProvider from "@/contexts/FetchContext";

export const dynamic = "force-dynamic";
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// fetchService
const serviceAPIUrl = `${process.env.NEXT_PUBLIC_BACK_END_URL}/api/v1/page/service`;
async function fetchService() {
  try {
    const response = await fetch(serviceAPIUrl, {
      method: "GET",
      cache: "no-store",
    });

    if (!response.ok) {
      throw new Error("Network response was not ok");
    }

    const data = await response.json();

    return data?.rows;
  } catch (error) {
    console.error("There was a problem with the fetch operation:", error);
  }
}

const roboto = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// const inter = Inter({ subsets: ["latin"] });
const languageTranslation = process.env.TRANSLATION_TYPE;
export const metadata: Metadata = {
  title: "HANKYU HANSHIN",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export const ico: Metadata = {
  title: "favicon",
  description: "By Owner",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default async function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: { lng: string };
}>) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body
        className={
          lng == "en"
            ? `${roboto.className}`
            : `${prompt.className} ${styles.text}`
        }
      >
        <ConfigProvider
          theme={{
            token: {
              fontFamily:
                lng == "en" ? roboto.style.fontFamily : prompt.style.fontFamily,
            },
          }}
        >
          <FetchProvider>
            <PageSettingProvider lng={lng}>
              <Header
                lng={lng}
                services={await fetchService()}
                font={prompt.className}
              />
              {children}
              <Footer lng={lng} services={await fetchService()} />
            </PageSettingProvider>
          </FetchProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}

// export default appWithTranslation(RootLayout);
